/*
 * File: app/controller/Circuit.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.Circuit', {
    extend: 'Ext.app.Controller',
    config: {
        control: {
            "#btn-details": {
                tap: 'afficherDetails'
            },
            "#btn-validerajoutcircuit": {
                tap: 'validerCircuit'
            },
            "#btn-carte": {
                tap: 'afficherCarte'
            },
            "#btn-circuits": {
                tap: 'afficherCircuits'
            },
            "#list-circuits": {
                select: 'afficherCircuit'
            },
            "#btn-ajoutcircuit": {
                tap: 'ajouterCircuit'
            },
            "#btn-apercu": {
                tap: 'afficherApercu'
            },
            "#btn-appareil": {
                tap: 'afficherAppareil'
            },
            "#btn-annulerajoutcircuit": {
                tap: 'annulerCircuit'
            }
        }
    },

    afficherDetails: function(button, e, options) {
        Ext.getCmp('panel-circuits').setActiveItem(Ext.getCmp('list-etapes'));
    },

    validerCircuit: function(button, e, options) {
        // Validations
        if (Ext.getCmp('textfield-nomcircuit').getValue() === '') return;
        if (Ext.getCmp('textfield-nomgroupe').getValue() === '') return; 
        if (Ext.getCmp('datefield-dategroupe').getValue() < new Date()) return;

        // Préparation de la date au format PHP
        var d = Ext.getCmp('datefield-dategroupe').getValue();
        var curr_date = d.getDate();
        var curr_month = d.getMonth() + 1; //months are zero based
        var curr_year = d.getFullYear();

        // Enregistrement du circuit
        Ext.Ajax.request({
            url: 'proxy.php?proxy_url=manager.php',
            params: {
                nomCircuit: Ext.getCmp('textfield-nomcircuit').getValue(),
                fn :'ajouterCircuit'
            },
            success: function(response){
                Ext.getCmp('list-circuits').getStore().load();

                // Enregistrement du groupe
                Ext.Ajax.request({
                    url: 'proxy.php?proxy_url=manager.php',
                    params: {
                        idCircuit: parseInt(response.responseText),
                        nomGroupe: Ext.getCmp('textfield-nomgroupe').getValue(),
                        dateGroupe: curr_year + "-" + curr_month + "-" + curr_date,
                        dureeGroupe: Ext.getCmp('slider-dureegroupe').getValue()[0],
                        fn :'ajouterGroupe'
                    },
                    success: function(response){
                        // Retour à la page de sélection des circuits
                        Ext.getCmp('panel-actions').setActiveItem(Ext.getCmp('panel-listes'));
                        Ext.getCmp('sgbtn-choixliste').setPressedButtons([Ext.getCmp('btn-circuits')]);
                    }
                });
            }
        });
    },

    afficherCarte: function(button, e, options) {
        Ext.getCmp('panel-circuits').setActiveItem(Ext.getCmp('carte'));
    },

    afficherCircuits: function(button, e, options) {
        // Afficher le titre
        Ext.getCmp('toolbar-titreliste').setTitle('Circuits');

        // Afficher le bouton btn-ajoutcircuit
        Ext.getCmp('btn-ajoutgroupe').hide();
        Ext.getCmp('btn-ajoutparticipant').hide();
        Ext.getCmp('btn-ajoutcircuit').show();

        // RAZ la list-participants
        Ext.getCmp('list-participants').deselectAll();

        // RAZ la list-groupes
        Ext.getCmp('list-groupes').deselectAll();

        // RAZ le panel-actions
        Ext.getCmp('panel-actions').setActiveItem(Ext.getCmp('panel-listes'));

        // Afficher le panel-aucuncircuit
        Ext.getCmp('panel-vues').setActiveItem(Ext.getCmp('panel-aucuncircuit'));

        // Afficher la list-circuits
        Ext.getCmp('panel-listes').setActiveItem(Ext.getCmp('list-circuits'));
    },

    afficherCircuit: function(dataview, record, options) {
        // Chargement des groupes du circuit
        Ext.getStore('Groupes').load({
            params:{
                fn: 'fetchGroupes',
                circuit_id: record.get('id')
            },
            callback:function(){
                // Afficher le titre
                Ext.getCmp('toolbar-titreliste').setTitle(record.get('nom'));

                // Afficher le bouton btn-ajoutgroupe    
                Ext.getCmp('btn-ajoutparticipant').hide();
                Ext.getCmp('btn-ajoutcircuit').hide();
                Ext.getCmp('btn-ajoutgroupe').show();

                // Afficher le bouton btn-retourcircuits
                Ext.getCmp('btn-retourcircuits').show();

                // Afficher la list-groupes et le panel-aucungroupe
                Ext.getCmp('panel-listes').setActiveItem(Ext.getCmp('list-groupes'));
                Ext.getCmp('panel-vues').setActiveItem(Ext.getCmp('panel-aucungroupe'));
            }
        });
    },

    ajouterCircuit: function(button, e, options) {
        Ext.getCmp('sgbtn-choixliste').setPressedButtons([]);
        Ext.getCmp('list-circuits').deselectAll();
        //Ext.getCmp('panel-vues').setActiveItem(Ext.getCmp('panel-photos'));
        alert('a malibu');
        Ext.getCmp('panel-vues').setActiveItem(Ext.getCmp('panel-ajoutcircuit'));
    },

    afficherApercu: function(button, e, options) {
        Ext.getCmp('panel-photos').setActiveItem(Ext.getCmp('panel-visualisation'));
    },

    afficherAppareil: function(button, e, options) {
        Ext.getCmp('panel-photos').setActiveItem(Ext.getCmp('panel-appareil'));
    },

    annulerCircuit: function(button, e, options) {
        Ext.getCmp('sgbtn-choixliste').setPressedButtons([Ext.getCmp('btn-circuits')]);
        Ext.getCmp('panel-vues').setActiveItem(Ext.getCmp('panel-aucuncircuit'));
        Ext.getCmp('panel-actions').setActiveItem(Ext.getCmp('panel-listes'));
    }

});