/*
 * File: app/controller/Groupe.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.Groupe', {
    extend: 'Ext.app.Controller',
    config: {
        control: {
            "#slider-dureegroupe": {
                drag: 'changerDuree'
            },
            "#list-groupes": {
                select: 'afficherGroupe'
            },
            "#btn-participantsgroupe": {
                tap: 'afficherParticipantsGroupe'
            },
            "#btn-validerparticipantsgroupe": {
                tap: 'validerParticipants'
            },
            "#list-participantsgroupe": {
                painted: 'onListPainted'
            },
            "#btn-ajoutgroupe": {
                tap: 'ajouterGroupe'
            },
            "#btn-annulerajoutgroupe": {
                tap: 'annulerGroupe'
            },
            "#btn-validerajoutgroupe": {
                tap: 'validerGroupe'
            },
            "#slider-dureeajoutgroupe": {
                drag: 'changerAjoutDuree'
            },
            "#btn-retourcircuits": {
                tap: 'retournerCircuits'
            }
        }
    },

    changerDuree: function(slider, Slider, thumb, e, options) {
        var newValue = slider.getValue()[0];
        var s = (newValue == 1 ? '' : 's');
        Ext.getCmp('slider-dureegroupe').setLabel('Durée<br />(' + newValue + ' jour' + s + ')');
    },

    afficherGroupe: function(dataview, record, options) {
        var me = this;

        // Charger les étapes du groupe séléctionné
        Ext.getStore('Etapes').load({
            params:{
                fn: 'fetchEtapes',
                circuit_id: Ext.getCmp('list-circuits').getSelection()[0].get('id')
            },
            callback:function(){
                me.getApplication().getController('Carte').effacerCircuit(Ext.getCmp('carte'));
                me.getApplication().getController('Carte').tracerCircuit(Ext.getStore('Etapes'), Ext.getCmp('carte'));
            }
        });

        // Afficher le titre
        Ext.getCmp('toolbar-titrecircuit').setTitle(record.get('nom')); 

        // Afficher le #panel-circuit
        Ext.getCmp('panel-vues').setActiveItem(Ext.getCmp('panel-circuits'));
    },

    afficherParticipantsGroupe: function(button, e, options) {
        Ext.getCmp('panel-participantsgroupe').showBy(Ext.getCmp('btn-participantsgroupe'), 'tr-bc?');
    },

    validerParticipants: function(button, e, options) {
        // Tableau des participants
        var participants = [];
        $('.done').each(function() {
            participants.push($(this).attr('participantid'));
        });

        // Enregistrement des participants
        Ext.Ajax.request({
            url: 'proxy.php?proxy_url=manager.php',
            params: {
                groupe_id: Ext.getCmp('list-groupes').getSelection()[0].get('id'),
                participants: participants.toString(),
                fn :'ajouterParticipants'
            },
            success: function(response){
                // Cacher le panel-participantsgroupe
                Ext.getCmp('panel-participantsgroupe').hide();
            }
        });
    },

    onListPainted: function(component, options) {
        // Charger les participations pour le groupe
        Ext.Ajax.request({
            url: 'proxy.php?proxy_url=manager.php',
            params: {
                groupe_id: Ext.getCmp('list-groupes').getSelection()[0].get('id'),
                fn :'fetchParticipations'
            },
            success: function(response){
                // Cocher les participants
                var participants = Ext.decode(response.responseText);

                for (var i = 0; i < participants.length; i++) {
                    var id = participants[i].participant_id;
                    $('span[participantid=' + id + ']').addClass('done');
                }
            }
        });
    },

    ajouterGroupe: function(button, e, options) {
        Ext.getCmp('sgbtn-choixliste').setPressedButtons([]);
        Ext.getCmp('list-groupes').deselectAll();
        Ext.getCmp('panel-vues').setActiveItem(Ext.getCmp('panel-photos'));
        Ext.getCmp('panel-actions').setActiveItem(Ext.getCmp('panel-ajoutgroupe'));
    },

    annulerGroupe: function(button, e, options) {
        Ext.getCmp('sgbtn-choixliste').setPressedButtons([Ext.getCmp('btn-circuits')]);
        Ext.getCmp('panel-vues').setActiveItem(Ext.getCmp('panel-aucungroupe'));
        Ext.getCmp('panel-actions').setActiveItem(Ext.getCmp('panel-listes'));
    },

    validerGroupe: function(button, e, options) {
        // Validations
        if (Ext.getCmp('textfield-nomajoutgroupe').getValue() === '') return; 
        if (Ext.getCmp('datefield-dateajoutgroupe').getValue() < new Date()) return;

        // Préparation de la date au format PHP
        var d = Ext.getCmp('datefield-dateajoutgroupe').getValue();
        var curr_date = d.getDate();
        var curr_month = d.getMonth() + 1; //months are zero based
        var curr_year = d.getFullYear();

        // Enregistrement du groupe
        Ext.Ajax.request({
            url: 'proxy.php?proxy_url=manager.php',
            params: {
                idCircuit: Ext.getCmp('list-circuits').getSelection()[0].get('id'),
                nomGroupe: Ext.getCmp('textfield-nomajoutgroupe').getValue(),
                dateGroupe: curr_year + "-" + curr_month + "-" + curr_date,
                dureeGroupe: Ext.getCmp('slider-dureeajoutgroupe').getValue()[0],
                fn :'ajouterGroupe'
            },
            success: function(response){
                // Recharger les groupes
                Ext.getCmp('list-groupes').getStore().load();

                // Chargement des groupes du circuit
                Ext.getStore('Groupes').load({
                    params:{
                        fn: 'fetchGroupes',
                        circuit_id: Ext.getCmp('list-circuits').getSelection()[0].get('id')
                    },
                    callback:function(){
                        // Afficher le titre
                        Ext.getCmp('toolbar-titreliste').setTitle(Ext.getCmp('list-circuits').getSelection()[0].get('nom'));

                        // Afficher la list-groupes et le panel-aucungroupe
                        Ext.getCmp('panel-listes').setActiveItem(Ext.getCmp('list-groupes'));
                        Ext.getCmp('panel-vues').setActiveItem(Ext.getCmp('panel-aucungroupe'));

                        // Retour à la page de sélection des circuits
                        Ext.getCmp('panel-actions').setActiveItem(Ext.getCmp('panel-listes'));
                        Ext.getCmp('sgbtn-choixliste').setPressedButtons([Ext.getCmp('btn-circuits')]);
                    }
                });
            }
        });
    },

    changerAjoutDuree: function(slider, Slider, thumb, e, options) {
        var newValue = slider.getValue()[0];
        var s = (newValue == 1 ? '' : 's');
        Ext.getCmp('slider-dureeajoutgroupe').setLabel('Durée<br />(' + newValue + ' jour' + s + ')');
    },

    retournerCircuits: function(button, e, options) {
        // Afficher le titre
        Ext.getCmp('toolbar-titreliste').setTitle('Circuits');

        // Afficher le bouton btn-ajoutcircuit
        Ext.getCmp('btn-ajoutgroupe').hide();
        Ext.getCmp('btn-ajoutparticipant').hide();
        Ext.getCmp('btn-ajoutcircuit').show();

        // RAZ la list-groupes
        Ext.getCmp('list-groupes').deselectAll();

        // RAZ la list-circuits
        Ext.getCmp('list-circuits').deselectAll();

        // RAZ le panel-actions
        Ext.getCmp('panel-actions').setActiveItem(Ext.getCmp('panel-listes'));

        // Afficher le panel-aucuncircuit
        Ext.getCmp('panel-vues').setActiveItem(Ext.getCmp('panel-aucuncircuit'));

        // Afficher la list-circuits
        Ext.getCmp('panel-listes').setActiveItem(Ext.getCmp('list-circuits'));

        // Cacher le btn-retourcircuits
        Ext.getCmp('btn-retourcircuits').hide();
    }

});