/*
 * File: app/controller/Participant.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.Participant', {
    extend: 'Ext.app.Controller',
    config: {
        control: {
            "#btn-participants": {
                tap: 'afficherParticipants'
            },
            "#list-participants": {
                select: 'afficherParticipant'
            },
            "#btn-ajoutparticipant": {
                tap: 'ajouterParticipant'
            },
            "#btn-annulerajoutparticipant": {
                tap: 'annulerParticipant'
            },
            "#btn-validerajoutparticipant": {
                tap: 'validerParticipant'
            }
        }
    },

    afficherParticipants: function(button, e, options) {
        // Afficher le titre
        Ext.getCmp('toolbar-titreliste').setTitle('Participants');

        // Afficher le bouton btn-ajoutparticipant
        Ext.getCmp('btn-ajoutcircuit').hide();
        Ext.getCmp('btn-ajoutgroupe').hide();
        Ext.getCmp('btn-ajoutparticipant').show();

        // RAZ la liste des circuits
        Ext.getCmp('list-circuits').deselectAll();

        // RAZ la list-groupes
        Ext.getCmp('list-groupes').deselectAll();

        // RAZ le panel-actions
        Ext.getCmp('panel-actions').setActiveItem(Ext.getCmp('panel-listes'));

        // Afficher le panel-aucunparticipant
        Ext.getCmp('panel-vues').setActiveItem(Ext.getCmp('panel-aucunparticipant'));

        // Afficher la list-participants
        Ext.getCmp('panel-listes').setActiveItem(Ext.getCmp('list-participants'));
    },

    afficherParticipant: function(dataview, record, options) {
        // Afficher la vue des informations
        Ext.getCmp('panel-vues').setActiveItem(Ext.getCmp('panel-participants'));

        // Mise à jour des champs d'information
        Ext.getCmp('toolbar-titreparticipant').setTitle(record.get('nom') + ' ' + record.get('prenom'));
        Ext.getCmp('telephone').setValue(record.get('tel'));
        Ext.getCmp('email').setValue(record.get('email'));
        Ext.getCmp('adresse').setValue(record.get('adresse'));
        Ext.getCmp('ville').setValue(record.get('ville'));
    },

    ajouterParticipant: function(button, e, options) {
        // RAZ des champs d'ajout du participant
        Ext.getCmp('textfield-nomparticipant').setValue('');
        Ext.getCmp('textfield-prenomparticipant').setValue('');
        Ext.getCmp('textfield-telparticipant').setValue(''); 
        Ext.getCmp('textfield-emailparticipant').setValue('');
        Ext.getCmp('select-villeparticipant').setValue(1);
        Ext.getCmp('textfield-adresseparticipant').setValue('');

        Ext.getCmp('sgbtn-choixliste').setPressedButtons([]);
        Ext.getCmp('list-participants').deselectAll();
        //Ext.getCmp('panel-vues').setActiveItem(Ext.getCmp('panel-photos'));
        alert('a malibu');
        Ext.getCmp('panel-vues').setActiveItem(Ext.getCmp('panel-ajoutparticipant'));
    },

    annulerParticipant: function(button, e, options) {
        Ext.getCmp('sgbtn-choixliste').setPressedButtons([Ext.getCmp('btn-participants')]);
        Ext.getCmp('panel-vues').setActiveItem(Ext.getCmp('panel-aucunparticipant'));
        Ext.getCmp('panel-actions').setActiveItem(Ext.getCmp('panel-listes'));
    },

    validerParticipant: function(button, e, options) {
        // Validations
        if (Ext.getCmp('textfield-nomparticipant').getValue() === '') return;
        if (Ext.getCmp('textfield-prenomparticipant').getValue() === '') return;
        if (Ext.getCmp('textfield-telparticipant').getValue() === '') return; 
        if (Ext.getCmp('textfield-emailparticipant').getValue() === '') return; 
        if (Ext.getCmp('textfield-adresseparticipant').getValue() === '') return; 

        // Enregistrement du participant
        Ext.Ajax.request({
            url: 'proxy.php?proxy_url=manager.php',
            params: {
                nom_participant: Ext.getCmp('textfield-nomparticipant').getValue(),
                prenom_participant: Ext.getCmp('textfield-prenomparticipant').getValue(),
                tel_participant: Ext.getCmp('textfield-telparticipant').getValue(),
                email_participant: Ext.getCmp('textfield-emailparticipant').getValue(),
                ville_participant: Ext.getCmp('select-villeparticipant').getValue(),
                adresse_participant: Ext.getCmp('textfield-adresseparticipant').getValue(),
                fn :'ajouterParticipant'
            },
            success: function(response){
                Ext.getCmp('list-participants').getStore().load();

                // Retour à la page de sélection des participants
                Ext.getCmp('panel-actions').setActiveItem(Ext.getCmp('panel-listes'));
                Ext.getCmp('sgbtn-choixliste').setPressedButtons([Ext.getCmp('btn-participants')]);
            }
        });
    }

});