/*
 * File: app/view/Viewport.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Viewport', {
    extend: 'Ext.Container',

    config: {
        id: 'viewport',
        layout: {
            type: 'hbox'
        },
        items: [
            {
                xtype: 'container',
                id: 'panel-actions',
                layout: {
                    type: 'card'
                },
                flex: 2,
                items: [
                    {
                        xtype: 'container',
                        id: 'panel-listes',
                        layout: {
                            type: 'card'
                        },
                        items: [
                            {
                                xtype: 'toolbar',
                                docked: 'top',
                                id: 'toolbar-titreliste',
                                title: 'Circuits',
                                layout: {
                                    pack: 'end',
                                    type: 'hbox'
                                },
                                items: [
                                    {
                                        xtype: 'button',
                                        hidden: true,
                                        id: 'btn-retourcircuits',
                                        ui: 'back',
                                        text: 'Retour'
                                    },
                                    {
                                        xtype: 'spacer'
                                    },
                                    {
                                        xtype: 'button',
                                        id: 'btn-ajoutcircuit',
                                        text: '+'
                                    },
                                    {
                                        xtype: 'button',
                                        hidden: true,
                                        id: 'btn-ajoutparticipant',
                                        text: '+'
                                    },
                                    {
                                        xtype: 'button',
                                        hidden: true,
                                        id: 'btn-ajoutgroupe',
                                        text: '+'
                                    }
                                ]
                            },
                            {
                                xtype: 'list',
                                id: 'list-circuits',
                                itemTpl: [
                                    '{nom}'
                                ],
                                loadingText: 'Chargement...',
                                store: 'Circuits',
                                allowDeselect: false
                            },
                            {
                                xtype: 'list',
                                id: 'list-participants',
                                itemTpl: [
                                    '{nom} {prenom}'
                                ],
                                loadingText: 'Chargement...',
                                store: 'Participants'
                            },
                            {
                                xtype: 'list',
                                id: 'list-groupes',
                                itemTpl: [
                                    '{nom}'
                                ],
                                loadingText: 'Chargement...',
                                store: 'Groupes'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        id: 'panel-ajoutcircuit',
                        ui: '',
                        hideOnMaskTap: false,
                        layout: {
                            type: 'vbox'
                        },
                        modal: false,
                        scrollable: 'false',
                        items: [
                            {
                                xtype: 'toolbar',
                                docked: 'top',
                                id: 'toolbar-ajoutcircuit',
                                title: 'Nouveau Circuit',
                                items: [
                                    {
                                        xtype: 'button',
                                        docked: 'left',
                                        id: 'btn-annulerajoutcircuit',
                                        margin: '10px',
                                        ui: 'decline',
                                        text: 'Annuler'
                                    },
                                    {
                                        xtype: 'button',
                                        docked: 'right',
                                        id: 'btn-validerajoutcircuit',
                                        margin: '10px',
                                        ui: 'confirm',
                                        text: 'Valider'
                                    }
                                ]
                            },
                            {
                                xtype: 'fieldset',
                                margin: 15,
                                title: 'Circuit',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        id: 'textfield-nomcircuit',
                                        label: 'Nom'
                                    }
                                ]
                            },
                            {
                                xtype: 'fieldset',
                                margin: 15,
                                title: 'Groupe',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        id: 'textfield-nomgroupe',
                                        label: 'Nom'
                                    },
                                    {
                                        xtype: 'datepickerfield',
                                        id: 'datefield-dategroupe',
                                        label: 'Date',
                                        placeHolder: 'mm/dd/yyyy',
                                        picker: {
                                            doneButton: 'Confirmer',
                                            cancelButton: 'Annuler'
                                        }
                                    },
                                    {
                                        xtype: 'sliderfield',
                                        id: 'slider-dureegroupe',
                                        label: 'Durée<br />(1 jour)',
                                        value: [
                                            1
                                        ],
                                        maxValue: 30,
                                        minValue: 1
                                    }
                                ]
                            },
                            {
                                xtype: 'dataview',
                                hidden: true,
                                id: 'dataview-imagecircuit',
                                padding: '10px',
                                itemTpl: [
                                    '<div style="clear: right; float: left; width:100px; margin-right: 10px"><img style="width:100px" src={url} /></div>'
                                ],
                                store: 'RemotePhotos',
                                flex: 1
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        id: 'panel-ajoutgroupe',
                        ui: '',
                        hideOnMaskTap: false,
                        layout: {
                            type: 'vbox'
                        },
                        modal: false,
                        scrollable: 'false',
                        items: [
                            {
                                xtype: 'toolbar',
                                docked: 'top',
                                id: 'toolbar-ajoutgroupe',
                                title: 'Nouveau Groupe',
                                items: [
                                    {
                                        xtype: 'button',
                                        docked: 'left',
                                        id: 'btn-annulerajoutgroupe',
                                        margin: '10px',
                                        ui: 'decline',
                                        text: 'Annuler'
                                    },
                                    {
                                        xtype: 'button',
                                        docked: 'right',
                                        id: 'btn-validerajoutgroupe',
                                        margin: '10px',
                                        ui: 'confirm',
                                        text: 'Valider'
                                    }
                                ]
                            },
                            {
                                xtype: 'fieldset',
                                margin: 15,
                                title: 'Groupe',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        id: 'textfield-nomajoutgroupe',
                                        label: 'Nom'
                                    },
                                    {
                                        xtype: 'datepickerfield',
                                        id: 'datefield-dateajoutgroupe',
                                        label: 'Date',
                                        placeHolder: 'mm/dd/yyyy',
                                        picker: {
                                            doneButton: 'Confirmer',
                                            cancelButton: 'Annuler'
                                        }
                                    },
                                    {
                                        xtype: 'sliderfield',
                                        id: 'slider-dureeajoutgroupe',
                                        label: 'Durée<br />(1 jour)',
                                        value: [
                                            1
                                        ],
                                        maxValue: 30,
                                        minValue: 1
                                    }
                                ]
                            },
                            {
                                xtype: 'dataview',
                                hidden: true,
                                id: 'dataview-imagecircuit',
                                padding: '10px',
                                itemTpl: [
                                    '<div style="clear: right; float: left; width:100px; margin-right: 10px"><img style="width:100px" src={url} /></div>'
                                ],
                                store: 'RemotePhotos',
                                flex: 1
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        id: 'panel-ajoutparticipant',
                        ui: '',
                        hideOnMaskTap: false,
                        layout: {
                            type: 'vbox'
                        },
                        modal: false,
                        scrollable: 'false',
                        items: [
                            {
                                xtype: 'toolbar',
                                docked: 'top',
                                id: 'toolbar-ajoutparticipant',
                                title: 'Nouveau Participant',
                                items: [
                                    {
                                        xtype: 'button',
                                        docked: 'left',
                                        id: 'btn-annulerajoutparticipant',
                                        margin: '10px',
                                        ui: 'decline',
                                        text: 'Annuler'
                                    },
                                    {
                                        xtype: 'button',
                                        docked: 'right',
                                        id: 'btn-validerajoutparticipant',
                                        margin: '10px',
                                        ui: 'confirm',
                                        text: 'Valider'
                                    }
                                ]
                            },
                            {
                                xtype: 'fieldset',
                                margin: 15,
                                title: 'Participant',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        id: 'textfield-nomparticipant',
                                        label: 'Nom'
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'textfield-prenomparticipant',
                                        label: 'Prenom'
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'textfield-telparticipant',
                                        label: 'Téléphone'
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'textfield-emailparticipant',
                                        label: 'Email'
                                    },
                                    {
                                        xtype: 'selectfield',
                                        id: 'select-villeparticipant',
                                        label: 'Ville',
                                        displayField: 'nom',
                                        store: 'Villes',
                                        valueField: 'id'
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'textfield-adresseparticipant',
                                        label: 'Adresse'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'toolbar',
                        docked: 'bottom',
                        id: 'toolbar-choixliste',
                        ui: 'light',
                        layout: {
                            pack: 'center',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'segmentedbutton',
                                id: 'sgbtn-choixliste',
                                items: [
                                    {
                                        xtype: 'button',
                                        id: 'btn-circuits',
                                        width: '100px',
                                        text: 'Circuits',
                                        pressed: true
                                    },
                                    {
                                        xtype: 'button',
                                        id: 'btn-participants',
                                        itemId: 'mybutton1',
                                        width: '100ox',
                                        text: 'Participants'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                id: 'panel-vues',
                style: 'border-left: 1px solid #000;',
                layout: {
                    type: 'card'
                },
                flex: 3,
                items: [
                    {
                        xtype: 'container',
                        html: 'Sélectionnez un circuit à gauche ou créez-en un nouveau',
                        id: 'panel-aucuncircuit',
                        style: 'padding-top: 10px; color: #666; text-shadow: rgba(255, 255, 255, 0.3) 0 1px 0; text-align: center; background: url(\'app/resource/image/noise.gif\')',
                        layout: {
                            type: 'fit'
                        }
                    },
                    {
                        xtype: 'container',
                        html: 'Sélectionnez un participant à gauche ou créez-en un nouveau',
                        id: 'panel-aucunparticipant',
                        style: 'padding-top: 10px; color: #666; text-shadow: rgba(255, 255, 255, 0.3) 0 1px 0; text-align: center; background: url(\'app/resource/image/noise.gif\')',
                        layout: {
                            type: 'fit'
                        }
                    },
                    {
                        xtype: 'container',
                        id: 'panel-circuits',
                        layout: {
                            type: 'card'
                        },
                        items: [
                            {
                                xtype: 'toolbar',
                                docked: 'top',
                                id: 'toolbar-titrecircuit',
                                title: '',
                                layout: {
                                    pack: 'end',
                                    type: 'hbox'
                                },
                                items: [
                                    {
                                        xtype: 'button',
                                        hidden: true,
                                        id: 'btn-annuleretape',
                                        text: 'Retour'
                                    },
                                    {
                                        xtype: 'spacer'
                                    },
                                    {
                                        xtype: 'button',
                                        id: 'btn-participantsgroupe',
                                        text: 'P'
                                    },
                                    {
                                        xtype: 'button',
                                        hidden: true,
                                        id: 'btn-activiteItems',
                                        text: '+'
                                    }
                                ]
                            },
                            {
                                xtype: 'map',
                                id: 'carte',
                                ui: ''
                            },
                            {
                                xtype: 'list',
                                id: 'list-etapes',
                                itemTpl: [
                                    '{nom}'
                                ],
                                store: 'Etapes'
                            },
                            {
                                xtype: 'panel',
                                height: 59,
                                hidden: true,
                                id: 'panel-menumarker',
                                showAnimation: 'fade',
                                ui: '',
                                width: 400,
                                hideOnMaskTap: true,
                                layout: {
                                    type: 'fit'
                                },
                                modal: true,
                                scrollable: false,
                                items: [
                                    {
                                        xtype: 'toolbar',
                                        docked: 'top',
                                        id: 'toolbar-menumarker',
                                        layout: {
                                            align: 'center',
                                            type: 'hbox'
                                        },
                                        items: [
                                            {
                                                xtype: 'button',
                                                id: 'btn-annulermarker',
                                                ui: 'decline',
                                                text: 'Annuler'
                                            },
                                            {
                                                xtype: 'textfield',
                                                id: 'textfield-nommarker'
                                            },
                                            {
                                                xtype: 'button',
                                                id: 'btn-validermarker',
                                                ui: 'confirm',
                                                text: 'OK',
                                                flex: 1
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                height: 500,
                                hidden: true,
                                id: 'panel-participantsgroupe',
                                showAnimation: 'fade',
                                ui: '',
                                width: 400,
                                hideOnMaskTap: true,
                                layout: {
                                    type: 'fit'
                                },
                                modal: true,
                                scrollable: false,
                                items: [
                                    {
                                        xtype: 'toolbar',
                                        docked: 'top',
                                        id: 'toolbar-participantsgroupe',
                                        style: 'background: #f7f7f7 !important; border: none !important; border-bottom: 1px solid #dedede !important',
                                        items: [
                                            {
                                                xtype: 'searchfield',
                                                id: 'search-filtrerparticipants',
                                                flex: 1
                                            },
                                            {
                                                xtype: 'button',
                                                id: 'btn-validerparticipantsgroupe',
                                                ui: 'confirm',
                                                text: 'Valider'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'list',
                                        id: 'list-participantsgroupe',
                                        itemTpl: [
                                            '<span style="clear:both;float:left;">{nom} {prenom}</span><span  style="float:right;margin-right:-12px;" participantid="{id}"  id="participant{id}" class="GoalInterCheck checkitem {[values.completed==true ? "done" : ""]}" onClick="javascript:toogleSelection(this);" />'
                                        ],
                                        store: 'Participants',
                                        disableSelection: true
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 300,
                                hidden: true,
                                id: 'panel-detailsmarker',
                                showAnimation: 'fade',
                                ui: '',
                                width: 400,
                                hideOnMaskTap: false,
                                layout: {
                                    type: 'fit'
                                },
                                scrollable: false,
                                items: [
                                    {
                                        xtype: 'toolbar',
                                        docked: 'top',
                                        id: 'toolbar-detailsmarker',
                                        layout: {
                                            align: 'center',
                                            type: 'hbox'
                                        },
                                        items: [
                                            {
                                                xtype: 'button',
                                                id: 'btn-annulerdetails',
                                                ui: 'decline',
                                                text: 'Annuler'
                                            },
                                            {
                                                xtype: 'button',
                                                id: 'btn-ajouteractivite',
                                                ui: 'confirm',
                                                text: '+',
                                                flex: 1
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        id: 'panel-information',
                                        ui: 'light',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                id: 'textfield-nomdetailetape',
                                                label: 'nom étape',
                                                name: 'nom etape'
                                            },
                                            {
                                                xtype: 'textareafield',
                                                id: 'textarea-descriptiondetailetape',
                                                label: 'Description'
                                            },
                                            {
                                                xtype: 'list',
                                                id: 'list-activitesdetailetape',
                                                itemTpl: [
                                                    '<div>List Item {string}</div>'
                                                ],
                                                store: 'store-activites'
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'toolbar',
                                docked: 'bottom',
                                id: 'toolbar-vuecircuit',
                                ui: 'light',
                                layout: {
                                    align: 'center',
                                    pack: 'center',
                                    type: 'hbox'
                                },
                                items: [
                                    {
                                        xtype: 'segmentedbutton',
                                        id: 'sgbtn-vuecircuit',
                                        items: [
                                            {
                                                xtype: 'button',
                                                id: 'btn-carte',
                                                width: '100px',
                                                text: 'Carte',
                                                pressed: true
                                            },
                                            {
                                                xtype: 'button',
                                                id: 'btn-details',
                                                itemId: 'mybutton1',
                                                width: '100px',
                                                text: 'Détails'
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                id: 'panel-detailsetape',
                                padding: 15,
                                items: [
                                    {
                                        xtype: 'fieldset',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                id: 'textfield-nometape',
                                                label: 'Nom'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'fieldset',
                                        items: [
                                            {
                                                xtype: 'textareafield',
                                                id: 'textarea-descriptionetape',
                                                label: 'Description'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'list',
                                        height: 200,
                                        id: 'list-activities',
                                        ui: 'round',
                                        itemTpl: [
                                            '{nom}'
                                        ],
                                        store: 'store-activites'
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                id: 'panel-formqs',
                                padding: 15,
                                items: [
                                    {
                                        xtype: 'fieldset',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                id: 'textfield-nomactiviteqs',
                                                label: 'Nom'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'fieldset',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                id: 'textfield-questionqs',
                                                label: 'Question'
                                            },
                                            {
                                                xtype: 'textfield',
                                                id: 'textfield-reponseqs',
                                                label: 'Réponse'
                                            },
                                            {
                                                xtype: 'textfield',
                                                id: 'textfield-pointsqs',
                                                label: 'Points'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'fieldset',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                id: 'textfield-indiceqs',
                                                label: 'Indice'
                                            },
                                            {
                                                xtype: 'textfield',
                                                id: 'textfield-malusqs',
                                                label: 'Malus'
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                id: 'panel-formqcm',
                                padding: 15,
                                items: [
                                    {
                                        xtype: 'fieldset',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                id: 'textfield-nomactiviteqcm',
                                                label: 'Nom'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'fieldset',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                id: 'textfield-questionqcm',
                                                label: 'Question'
                                            },
                                            {
                                                xtype: 'textfield',
                                                id: 'textfield-pointsqcm',
                                                label: 'Points'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'fieldset',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                id: 'textfield-indiceqcm',
                                                label: 'Indice'
                                            },
                                            {
                                                xtype: 'textfield',
                                                id: 'textfield-malusqcm',
                                                label: 'Malus'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'list',
                                        height: 200,
                                        id: 'list-reponseqcm',
                                        ui: 'round',
                                        itemTpl: [
                                            '<tpl if="juste == \'Vrai\'">✔        </tpl><tpl if="juste == \'Faux\'">✘         </tpl>{reponse}<div class="deleteplaceholder" style="position: absolute; right: 20px; top :6px"></div>'
                                        ],
                                        store: 'ReponsesQcm'
                                    },
                                    {
                                        xtype: 'fieldset',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                id: 'textfield-ajouterreponse',
                                                value: 'Réponse',
                                                readOnly: true
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                id: 'panel-formgeoloc',
                                padding: 15,
                                items: [
                                    {
                                        xtype: 'fieldset',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                id: 'textfield-nomactivitegeoloc',
                                                label: 'Nom'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'fieldset',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                id: 'textfield-pointsgeoloc',
                                                label: 'Points'
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                id: 'panel-ajouterreponse',
                                padding: 15,
                                items: [
                                    {
                                        xtype: 'fieldset',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                id: 'textfield-reponseqcm',
                                                label: 'Réponse'
                                            },
                                            {
                                                xtype: 'checkboxfield',
                                                id: 'checkbox-reponsejuste',
                                                label: 'Juste'
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                id: 'panel-modifierreponse',
                                padding: 15,
                                items: [
                                    {
                                        xtype: 'fieldset',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                id: 'textfield-modifierreponseqcm',
                                                label: 'Réponse'
                                            },
                                            {
                                                xtype: 'checkboxfield',
                                                id: 'checkbox-modifierreponsejuste',
                                                label: 'Juste'
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                id: 'panel-detailsactivite',
                                layout: {
                                    type: 'card'
                                },
                                items: [
                                    {
                                        xtype: 'panel',
                                        id: 'panel-detailsqs',
                                        padding: 15,
                                        items: [
                                            {
                                                xtype: 'fieldset',
                                                items: [
                                                    {
                                                        xtype: 'textfield',
                                                        id: 'textfield-detailsnomactiviteqs',
                                                        label: 'Nom',
                                                        readOnly: true
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'fieldset',
                                                items: [
                                                    {
                                                        xtype: 'textfield',
                                                        id: 'textfield-detailsquestionqs',
                                                        label: 'Question',
                                                        readOnly: true
                                                    },
                                                    {
                                                        xtype: 'textfield',
                                                        id: 'textfield-detailsreponseqs',
                                                        label: 'Réponse',
                                                        readOnly: true
                                                    },
                                                    {
                                                        xtype: 'textfield',
                                                        id: 'textfield-detailspointsqs',
                                                        label: 'Points',
                                                        readOnly: true
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'fieldset',
                                                items: [
                                                    {
                                                        xtype: 'textfield',
                                                        id: 'textfield-detailsindiceqs',
                                                        label: 'Indice',
                                                        readOnly: true
                                                    },
                                                    {
                                                        xtype: 'textfield',
                                                        id: 'textfield-detailsmalusqs',
                                                        label: 'Malus',
                                                        readOnly: true
                                                    }
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        id: 'panel-detailsqcm',
                                        padding: 15,
                                        items: [
                                            {
                                                xtype: 'fieldset',
                                                items: [
                                                    {
                                                        xtype: 'textfield',
                                                        id: 'textfield-detailsnomactiviteqcm',
                                                        label: 'Nom',
                                                        readOnly: true
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'fieldset',
                                                items: [
                                                    {
                                                        xtype: 'textfield',
                                                        id: 'textfield-detailsquestionqcm',
                                                        label: 'Question',
                                                        readOnly: true
                                                    },
                                                    {
                                                        xtype: 'textfield',
                                                        id: 'textfield-detailspointsqcm',
                                                        label: 'Points',
                                                        readOnly: true
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'fieldset',
                                                items: [
                                                    {
                                                        xtype: 'textfield',
                                                        id: 'textfield-detailsindiceqcm',
                                                        label: 'Indice',
                                                        readOnly: true
                                                    },
                                                    {
                                                        xtype: 'textfield',
                                                        id: 'textfield-detailsmalusqcm',
                                                        label: 'Malus',
                                                        readOnly: true
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'list',
                                                height: 200,
                                                id: 'list-detailsreponsesqcm',
                                                ui: 'round',
                                                itemTpl: [
                                                    '<tpl if="juste == \'1\'">✔        </tpl><tpl if="juste == \'0\'">✘         </tpl>{reponse}<div class="deleteplaceholder" style="position: absolute; right: 20px; top :6px"></div>'
                                                ],
                                                store: 'ReponsesQcm'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        id: 'panel-detailsgeoloc',
                                        padding: 15,
                                        items: [
                                            {
                                                xtype: 'fieldset',
                                                items: [
                                                    {
                                                        xtype: 'textfield',
                                                        id: 'textfield-detailsnomactivitegeoloc',
                                                        label: 'Nom',
                                                        readOnly: true
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'fieldset',
                                                items: [
                                                    {
                                                        xtype: 'textfield',
                                                        id: 'textfield-detailspointsgeoloc',
                                                        label: 'Points',
                                                        readOnly: true
                                                    }
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        id: 'panel-detailsmodifierreponse',
                                        padding: 15,
                                        items: [
                                            {
                                                xtype: 'fieldset',
                                                items: [
                                                    {
                                                        xtype: 'textfield',
                                                        id: 'textfield-detailsmodifierreponseqcm',
                                                        label: 'Réponse'
                                                    },
                                                    {
                                                        xtype: 'checkboxfield',
                                                        id: 'checkbox-detailsmodifierreponsejuste',
                                                        label: 'Juste'
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                height: 153,
                                hidden: true,
                                id: 'panel-menuetape',
                                width: 350,
                                hideOnMaskTap: true,
                                layout: {
                                    type: 'fit'
                                },
                                modal: true,
                                items: [
                                    {
                                        xtype: 'list',
                                        id: 'list-choixtypeactivite',
                                        itemTpl: [
                                            '{nom}'
                                        ],
                                        store: 'store-typeActivite'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        id: 'panel-participants',
                        layout: {
                            type: 'card'
                        },
                        items: [
                            {
                                xtype: 'toolbar',
                                docked: 'top',
                                id: 'toolbar-titreparticipant',
                                title: '',
                                layout: {
                                    pack: 'end',
                                    type: 'hbox'
                                }
                            },
                            {
                                xtype: 'container',
                                id: 'panel-detailsparticipant',
                                items: [
                                    {
                                        xtype: 'fieldset',
                                        margin: 15,
                                        title: 'Informations',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                id: 'telephone',
                                                label: 'Téléphone',
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                id: 'email',
                                                label: 'Email',
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                id: 'ville',
                                                label: 'Ville',
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                id: 'adresse',
                                                label: 'Adresse',
                                                readOnly: true
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                id: 'panel-participations'
                            },
                            {
                                xtype: 'toolbar',
                                docked: 'bottom',
                                id: 'toolbar-vueparticipant',
                                ui: 'light',
                                layout: {
                                    pack: 'center',
                                    type: 'hbox'
                                },
                                items: [
                                    {
                                        xtype: 'segmentedbutton',
                                        id: 'sgbtn-vueparticipant',
                                        items: [
                                            {
                                                xtype: 'button',
                                                id: 'btn-infosparticipant',
                                                width: '150px',
                                                text: 'Informations',
                                                pressed: true
                                            },
                                            {
                                                xtype: 'button',
                                                id: 'btn-participationsparticipant',
                                                width: '150px',
                                                text: 'Participations'
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        id: 'panel-photos',
                        layout: {
                            type: 'card'
                        },
                        items: [
                            {
                                xtype: 'toolbar',
                                docked: 'top',
                                id: 'toolbar-titrephoto',
                                title: 'Prévisualisation de l\'image',
                                layout: {
                                    pack: 'end',
                                    type: 'hbox'
                                }
                            },
                            {
                                xtype: 'container',
                                html: 'Placeholder pour l\'appareil photo.',
                                id: 'panel-appareil',
                                styleHtmlContent: true
                            },
                            {
                                xtype: 'container',
                                html: 'Sélectionnez une photo à visualiser.',
                                id: 'panel-visualisation',
                                styleHtmlContent: true
                            },
                            {
                                xtype: 'toolbar',
                                docked: 'bottom',
                                id: 'toolbar-vuephoto',
                                ui: 'light',
                                layout: {
                                    pack: 'center',
                                    type: 'hbox'
                                },
                                items: [
                                    {
                                        xtype: 'segmentedbutton',
                                        id: 'sgbtn-vuephoto',
                                        items: [
                                            {
                                                xtype: 'button',
                                                id: 'btn-appareil',
                                                width: '100px',
                                                text: 'Appareil',
                                                pressed: true
                                            },
                                            {
                                                xtype: 'button',
                                                id: 'btn-apercu',
                                                width: '100px',
                                                text: 'Aperçu'
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        html: 'Sélectionnez un groupe à gauche ou créez-en un nouveau',
                        id: 'panel-aucungroupe',
                        style: 'padding-top: 10px; color: #666; text-shadow: rgba(255, 255, 255, 0.3) 0 1px 0; text-align: center; background: url(\'app/resource/image/noise.gif\')',
                        layout: {
                            type: 'fit'
                        }
                    }
                ]
            }
        ]
    }

});